projects:
  AmpNuxt3GraphQLAPI:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.t
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: api/index.ts
        docsFilePath: graphql
extensions:
  amplify:
    version: 3
